test:
  api:
    url: ${TEST_API_URL:https://petstore.swagger.io/v2}
    username: ${TEST_API_USERNAME:admin}
    password: ${TEST_API_PASSWORD:admin}
  ui:
    url: ${TEST_UI_URL:https://www.google.com/}
    username: ${TEST_UI_USERNAME:autotest}
    password: ${TEST_UI_PASSWORD:autotest}
  db:
    url: ${TEST_DB_URL:jdbc:p6spy:postgresql://localhost:5432/testdb}
    username: ${TEST_DB_USERNAME:testuser}
    password: ${TEST_DB_PASSWORD:testpassword}